server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/customer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Isi6426192,
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  # ← CAMBIA ESTO
    prefer-ip-address: true
    hostname: localhost