server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true  # ← AGREGAR ESTO

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Herramientas
        - id: tools-service
          uri: lb://tools-service
          predicates:
            - Path=/api/tools/**
          filters:
            - StripPrefix=0

        # Préstamos
        - id: loans-service
          uri: lb://loans-service
          predicates:
            - Path=/api/loans/**
          filters:
            - StripPrefix=0

        # Clientes
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customers/**

        # Tarifas
        - id: tariffs-service
          uri: lb://tariffs-service
          predicates:
            - Path=/api/tariffs/**
          filters:
            - StripPrefix=0

        # Kardex
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/api/kardex/**
          filters:
            - StripPrefix=0

        # Reportes
        - id: reports-service
          uri: lb://reports-service
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=0

        # Usuarios
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG