server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3313/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Isi6426192,
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

keycloak:
  auth-server-url: http://localhost:8082
  realm: toolrent-realm
  client-id: toolrent-backend
  client-secret: t2IHk5XC0vWwXVhHMvoxN7BvxkBFrnqA